# Auto-generated by scripts/calibrate.py — do not edit by hand.
# Source: Cinderhaven Postgres percentile distributions (2023-2026 window).
# Re-run calibrate.py against updated data before changing thresholds.

# Scoring direction: 5 = best, 1 = worst.
# For "lower is better" dimensions (shelf_space_cost, production_complexity,
# cannibalization_risk), score 5 is assigned at LOW raw values.

# --- Velocity (units/store/week) ---
# Score 5: >= p75, Score 4: p50–p75, Score 3: p25–p50,
# Score 2: p10–p25, Score 1: < p10
VELOCITY_P10 = 2.0201
VELOCITY_P25 = 4.3606
VELOCITY_P50 = 8.3338
VELOCITY_P75 = 13.5066
VELOCITY_P90 = 18.2600

# --- Contribution margin (loaded_margin_pct, 0.0–1.0) ---
MARGIN_P10 = -7.7654
MARGIN_P25 = -6.9733
MARGIN_P50 = -4.7576
MARGIN_P75 = -4.3700
MARGIN_P90 = -3.9764

# --- Shelf-space cost (annual USD) — lower is better ---
# Score 5: ≤ p25, Score 4: p25–p50, Score 3: p50–p75,
# Score 2: p75–p90, Score 1: > p90
SHELF_P10 = 24128.67
SHELF_P25 = 40136.32
SHELF_P50 = 74765.20
SHELF_P75 = 119627.83
SHELF_P90 = 137925.29

# --- Production complexity proxy (landed_cost/msrp ratio) — lower is better ---
COMPLEX_P10 = 0.2284
COMPLEX_P25 = 0.2475
COMPLEX_P50 = 0.2701
COMPLEX_P75 = 0.3012
COMPLEX_P90 = 0.3167

# --- Cannibalization risk (inverted velocity delta) — lower is better ---
# 0.0 = no signal, positive = velocity drops in shared stores
CANNIBAL_P10 = 0.0000
CANNIBAL_P25 = 0.0000
CANNIBAL_P50 = 0.0000
CANNIBAL_P75 = 0.0745
CANNIBAL_P90 = 0.2054
